# Generated by Django 3.0.8 on 2020-07-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='is_deleted',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
