# Generated by Django 3.0.8 on 2020-07-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200731_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='is_deleted',
            field=models.IntegerField(default=0),
        ),
    ]
