# Generated by Django 2.0.13 on 2020-08-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200731_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('login_name', models.CharField(max_length=100)),
                ('user_pwd', models.CharField(max_length=100)),
                ('nick_name', models.CharField(max_length=100)),
                ('locked', models.IntegerField(default=0)),
                ('introduce', models.CharField(max_length=100)),
                ('is_deleted', models.IntegerField(default=0)),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mall_user',
            },
        ),
    ]
